server:
  port: 8090

logging:
  level:
    org.springframework: INFO
    com.pyro.advance.recharge: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file:
    name: advanceRechage.log

spring:
  #h2:
    #console:
      #enabled: true
  datasource:
    #url: jdbc:h2:mem:testdb
    #driver-class-name: org.h2.Driver
    #platform: org.hibernate.dialect.H2Dialect
    #username: SA
    #password: password
    hikari:
      connection-timeout: 20000 #maximum number of milliseconds that a client will wait for a connection
      minimum-idle: 10 #minimum number of idle connections maintained by HikariCP in a connection pool
      maximum-pool-size: 10 #maximum pool size
      idle-timeout: 10000 #maximum idle time for connection
      max-lifetime: 1000 # maximum lifetime in milliseconds of a connection in the pool after it is closed.
      auto-commit: true #default auto-commit behavior.
  jpa:
    show-sql: true

tps:
  otaXmlResponse: 1

landlineBillPayUrl: http://10.147.235.21:19202/LandlineTPS/cellonebillpay.action?
landlineBillEnquiryUrl: http://10.147.235.21:19202/LandlineTPS/cellonebillenquiry.action?
postpaidBillPay: http://10.147.235.21:1579/CPBMultiwallet/cellonebillpay.action?
postpaidBillEnquiry: http://10.147.235.21:1579/CPBMultiwallet/cellonebillenquiry.action?
inputTypeMultiWallet: MCBP
walletType: CBP
encrypted: 1